### ISSUE TITLE
'Invalid signature' response on AWS

### ISSUE THREAD

**Issue by lyudad** [bitpay/node-bitpay-client#97]
I receive error: `Error: { error: 'Invalid signature' }` on request  `GET: https://test.bitpay.com:443/tokens`. But signature is right because I can get token via Postman using the same headers.

I'm using `bitpay-rest` lib and AWS Lambda.

**Comment by DomIn3339** [comment]
Any update?

**Comment by danescsvn** [comment]
@DomIn3339 @lyudad we just pushed a new version of the client that fixes this issue. Please clone the latest version and let us know if you have any issues with it. 

Under root directory run the following: 
> npm run setup
> npm install

Thank you.

**Comment by lyudad** [comment]
![imageedit_2_4393732238](https://user-images.githubusercontent.com/25103090/45263701-58c05200-b437-11e8-8d90-15514860b081.gif)

version was not updated

**Comment by lyudad** [comment]
I have also checked code in node_modules in rest-client.js same code as was

**Comment by lyudad** [comment]
I have download library from github and install manually to project, have same issue. Let me know if you need any details

**Comment by pieterpoorthuis** [comment]
@lyudad we pushed 0.3.2 a week ago. Does this work for you?
See https://www.npmjs.com/package/bitpay-rest

**Comment by lyudad** [comment]
Hello, no. I have commented above after new library release

**Comment by pieterpoorthuis** [comment]
At the time of your post we had 0.3.1 as the latest version. Can you verify you tested 0.3.2?

**Comment by lyudad** [comment]
yes, you have pushed to github, but not to npm, so I install manually, I have checked again today, I still have the same. Need I instal some additional libraries to make it work?

**Comment by lyudad** [comment]
Also I notice that on other computer with ubunta it work, but on macOS and debian no

**Comment by danescsvn** [comment]
@lyudad if you could please run the following command on a new/different directory would be great. We have pushed a new version to NPM, 0.3.2 https://www.npmjs.com/package/bitpay-rest

> npm install bitpay-rest

You should see the same experience on MacOS, that is what we use here. Please confirm and send a secreenshot if you can. Thank you. 

Cheers,
DDE
